import { contextBridge, ipcRenderer } from "electron";
import type { CardShowPayload, MetriaApi, ProviderKind, ProviderSourceChoice, SpendDisplay, WidgetBehavior, WidgetEdge, WidgetSize } from "../shared/types";

const api: MetriaApi = {
  getUsage: () => ipcRenderer.invoke("metria:get-usage"),
  refresh: () => ipcRenderer.invoke("metria:refresh"),
  openDashboard: () => ipcRenderer.invoke("metria:open-dashboard"),
  setProviderHover: (index: number | null) => ipcRenderer.invoke("metria:provider-hover", index),
  resizeCard: (height: number) => ipcRenderer.invoke("metria:card-resize", height),
  onSettingsChanged: (callback: () => void) => { ipcRenderer.on("metria:settings-changed", () => callback()); },
  onCardShow: (callback: (payload: CardShowPayload) => void) => { ipcRenderer.on("metria:card-show", (_event, payload: CardShowPayload) => callback(payload)); },
  onCardHide: (callback: () => void) => { ipcRenderer.on("metria:card-hide", () => callback()); },
  getSettings: () => ipcRenderer.invoke("metria:get-settings"),
  setProviderEnabled: (kind: ProviderKind, enabled: boolean) => ipcRenderer.invoke("metria:set-provider-enabled", kind, enabled),
  reconnect: (kind: ProviderKind) => ipcRenderer.invoke("metria:reconnect", kind),
  setWidgetYOffset: (offsetY: number) => ipcRenderer.invoke("metria:set-widget-y-offset", offsetY),
  getLoginItemStatus: () => ipcRenderer.invoke("metria:get-login-item-status"),
  setLaunchAtLogin: (enabled: boolean) => ipcRenderer.invoke("metria:set-launch-at-login", enabled),
  getAppInfo: () => ipcRenderer.invoke("metria:app-info"),
  checkUpdates: () => ipcRenderer.invoke("metria:check-updates"),
  installUpdate: () => ipcRenderer.invoke("metria:install-update"),
  uninstall: () => ipcRenderer.invoke("metria:uninstall"),
  quit: () => ipcRenderer.invoke("metria:quit"),
  setRefreshInterval: (seconds: number) => ipcRenderer.invoke("metria:set-refresh-interval", seconds),
  setSpendDisplay: (display: SpendDisplay) => ipcRenderer.invoke("metria:set-spend-display", display),
  setShowAccountLabels: (show: boolean) => ipcRenderer.invoke("metria:set-account-labels", show),
  setWindowHidden: (kind: ProviderKind, title: string, hidden: boolean) => ipcRenderer.invoke("metria:set-window-hidden", kind, title, hidden),
  setWidgetSize: (size: WidgetSize) => ipcRenderer.invoke("metria:set-widget-size", size),
  setWidgetEdge: (edge: WidgetEdge) => ipcRenderer.invoke("metria:set-widget-edge", edge),
  setWidgetBehavior: (behavior: WidgetBehavior) => ipcRenderer.invoke("metria:set-widget-behavior", behavior),
  setWidgetDisplay: (displayId: number | null) => ipcRenderer.invoke("metria:set-widget-display", displayId),
  getDisplays: () => ipcRenderer.invoke("metria:get-displays"),
  setWidgetHover: (hovering: boolean) => ipcRenderer.invoke("metria:widget-hover", hovering),
  getProviderSources: () => ipcRenderer.invoke("metria:get-provider-sources"),
  setProviderSource: (kind: ProviderKind, source: ProviderSourceChoice) => ipcRenderer.invoke("metria:set-provider-source", kind, source),
  getPairing: () => ipcRenderer.invoke("metria:get-pairing"),
  regeneratePairing: () => ipcRenderer.invoke("metria:regenerate-pairing"),
  setNtfyServer: (server: string) => ipcRenderer.invoke("metria:set-ntfy-server", server),
  setLocalServerPort: (port: number) => ipcRenderer.invoke("metria:set-local-server-port", port),
  setCustomPwaUrl: (url: string) => ipcRenderer.invoke("metria:set-custom-pwa-url", url),
  copyText: (text: string) => ipcRenderer.invoke("metria:copy-text", text),
  onPairingChanged: (callback: () => void) => { ipcRenderer.on("metria:pairing-changed", () => callback()); }
};

contextBridge.exposeInMainWorld("metria", Object.freeze(api));
